In [2]:
import requests
import pandas as pd
import sqlite3
import time
import json

API_KEY = "3155e101354aec2537082ac90b3aee9e"

movies = []
url = "https://api.themoviedb.org/3/discover/movie"

headers = {
    "User-Agent": "Mozilla/5.0"
}

for page in range(1, 3):
    params = {
        "api_key": API_KEY,
        "page": page
    }
    
    try:
        response = requests.get(url, params=params, headers=headers, timeout=10)
        response.raise_for_status()
        
        data = response.json()
        
        if 'results' in data:
            movies.extend(data['results'])
        
        time.sleep(1)
        
    except Exception as e:
        print("Error:", e)

if len(movies) == 0:
    print(" No data fetched. Check API key or network.")

else:
    df = pd.DataFrame(movies)
    
    if 'genre_ids' in df.columns:
        df['genre_ids'] = df['genre_ids'].apply(lambda x: json.dumps(x) if isinstance(x, list) else x)
    
    conn = sqlite3.connect("movies.db")
    df.to_sql("movies", conn, if_exists="replace", index=False)
    
    df = pd.read_sql("SELECT * FROM movies", conn)
    conn.close()
    
    
    print("\n DATA FETCHED SUCCESSFULLY")
    
    print("\n Shape of Data:")
    display(pd.DataFrame({"Rows": [df.shape[0]], "Columns": [df.shape[1]]}))
    
    print("\n First 5 Rows:")
    display(df.head())
    
    print("\n Summary Statistics:")
    display(df.describe())
    
    print("\n Missing Values:")
    display(df.isnull().sum().to_frame(name="Missing Count"))
    
    print("\n Top Genre Counts:")
    display(df['genre_ids'].value_counts().head().to_frame(name="Count"))

 DATA FETCHED SUCCESSFULLY

 Shape of Data:

   Rows  Columns
0    40       14

 First 5 Rows:

,adult,backdrop_path,genre_ids,id,original_language,original_title,overview,popularity,poster_path,release_date,title,video,vote_average,vote_count
0,0,/1x9e0qWonw634NhIsRdvnneeqvN.jpg,"[10749, 18]",1523145,ru,Твоё сердце будет разбито,High school student Polina is saved from bully...,1165.1266,/7wIBfBl2gejt6xHxNSK0reVIm7E.jpg,2026-03-26,Your Heart Will Be Broken,0,6.827,26
1,0,/u8DU5fkLoM5tTRukzPC31oGPxaQ.jpg,"[878, 12, 14]",83533,en,Avatar: Fire and Ash,In the wake of the devastating war against the...,503.6662,/bRBeSHfGHwkEpImlhxPmOcUsaeg.jpg,2025-12-17,Avatar: Fire and Ash,0,7.309,2084
2,0,/uNToXatdunyvWXyXMrTI1nLvh6r.jpg,"[35, 878, 80]",1115544,en,Mike & Nick & Nick & Alice,Two gangsters and the woman they love try to s...,352.9397,/7F0jc75HrSkLVcvOXR2FXAIwuEv.jpg,2026-03-14,Mike & Nick & Nick & Alice,0,6.700,109
3,0,/6GuqUJ33BnWDAoVPZP55gDr5G55.jpg,"[28, 53, 10402]",1084187,en,Pretty Lethal,A troupe of ballerinas find themselves fightin...,311.0726,/znTPnXCK3lEQJgqXCvP7e5FUz6f.jpg,2026-03-13,Pretty Lethal,0,6.745,159
4,0,/nHxWyy18SvAZ8jJeemtS8k1UNjM.jpg,"[28, 80, 53]",1290821,en,Shelter,A man living in self-imposed exile on a remote...,308.3847,/buPFnHZ3xQy6vZEHxbHgL1Pc6CR.jpg,2026-01-28,Shelter,0,6.751,442

 Summary Statistics:

       adult            id   popularity  video  vote_average    vote_count
count   40.0  4.000000e+01    40.000000   40.0     40.000000     40.000000
mean     0.0  1.113495e+06   171.956862    0.0      6.747800   1020.150000
std      0.0  3.429845e+05   188.115375    0.0      0.986769   3406.242765
min      0.0  8.353300e+04    54.824200    0.0      4.149000      1.000000
25%      0.0  8.725558e+05    84.560625    0.0      6.214250     38.750000
50%      0.0  1.169668e+06   100.782100    0.0      6.952000    279.500000
75%      0.0  1.319024e+06   180.426900    0.0      7.311500    791.750000
max      0.0  1.634301e+06  1165.126600    0.0      8.500000  21722.000000

 Missing Values:

                   Missing Count
adult                          0
backdrop_path                  0
genre_ids                      0
id                             0
original_language              0
original_title                 0
overview                       0
popularity                     0
poster_path                    0
release_date                   0
title                          0
video                          0
vote_average                   0
vote_count                     0

 Top Genre Counts:

               Count
genre_ids
[10749, 18]        2
[28, 80, 53]       2
[27]               2
[878, 12, 14]      1
[35, 878, 80]      1